### PR TITLE
Add missing dependencies: sphinx, sphinx_rtd_theme, matplotlib.

### PR DESCRIPTION
**Pull request by qiuwch**
Add missing dependencies.
Tested in a clean docker container.

### CODE REVIEW

**Comment by chsasank** [comment]
Please add `pillow` to requirements as well just in case.  

from sphinx gallery's read me:
> Sphinx-Gallery will not manage its dependencies when installing, thus you are required to install them manually. Our minimal dependencies are:
> 
> Sphinx
> Matplotlib
> Pillow

Thanks :)

**Comment by qiuwch** [comment]
Pillow is installed during the installation of pytorch and torchvision. That's why I don't include it.

**Comment by chsasank** [comment]
Oh right, then add `torchvision` to requirements. Ideally, torch should be added too, but there's no simple way to install it across OS without conda.

**Comment by qiuwch** [comment]
Ok, done.

**Comment by chsasank** [comment]
Thank a lot @qiuwch !

**Comment by qiuwch** [comment]
My pleasure. This is a very well-organized tutorials repository.

**Pull request merged**
