### PR TITLE
fine tuned intel_extension_for_pytorch.

### PR DESCRIPTION
**Pull request by jingxu10**
1. moved intel_extension_for_pytorch.py to intel_extension_for_pytorch.rst to make it compatible to cpp source codes.
2. fixed bug of Float32 level missing in the right side extractable navigation bar.

### CODE REVIEW

**Comment by jingxu10** [comment]
Hi @yqhu , I've just rebased the PR to the latest master branch. Could you approve it again and merge it? Thank you.

**Review by yqhu — APPROVED** [review]

**Comment by jingxu10** [comment]
@yqhu Eh... It got out-of-date again... I updated the branch, please approve merge it. Thanks a lot!

**Review by yqhu — APPROVED** [review]
Thanks @jingxu10

**Comment by jingxu10** [comment]
Hi @yqhu , thanks for approving. Could you please request someone to get this PR merged? It will be out-of-date again had other PRs merged... Thank you.

**Review by yqhu — APPROVED** [review]

**Comment by jingxu10** [comment]
Thanks a lot!

**Pull request merged**
