### PR TITLE
Render images in certain Blitz, Basics, and Youtube tutorial notebooks

### PR DESCRIPTION
**Pull request by kiersten-stokes**
This PR adds a root image path to the `sphinx_gallery_conf` dict according to [these instructions](https://sphinx-gallery.github.io/stable/configuration.html#notebook-images) given in the Sphinx Gallery docs. It also updates the corresponding relative paths in the `image` directives in certain Blitz, Basics, and Youtube tutorials.

Related to #791. I'm not going to link a 'closing' keyword yet, as this PR 1. addresses just a subset of the tutorials, and 2. may not be a viable solution (pending testing on the deploy preview).

Since this is affecting a project conf that I may not have historical knowledge as to why this wasn't used previously, I fully understand if we're not able to incorporate this one!

### CODE REVIEW

**Comment by kiersten-stokes** [comment]
I have a question for someone more knowledgeable than me (@svekars 🙂). After building with `make html`, the notebook file created in the `_build/html/_downloads` directory looks like the below screenshot, with the image rendered as expected.

Screenshot 2023-02-21 at 5 40 51 PM

Is this the version notebook that would be available via the `Run in Colab` link once (hypothetically) the PR is merged?

**Comment by svekars** [comment]
Thanks, Kiersten. I'm not sure why we'd want this and what's the actual value. Can you please elaborate?

**Comment by svekars** [comment]
Oh, I see. This definetely looks useful, although I'm not 100% sure if this would work. Let me check around and get back to you.

**Comment by kiersten-stokes** [comment]
> Oh, I see. This definetely looks useful, although I'm not 100% sure if this would work. Let me check around and get back to you.

@svekars any update? No hurry, just suddenly remembered that I had this one open 😄

**Pull request closed without merging**
