### PR TITLE
Address comments on Dist Profiling Recipe

### PR DESCRIPTION
**Pull request by rohan-varma**
Addresses @mrshenli 's comments on https://github.com/pytorch/tutorials/pull/1068

### CODE REVIEW

**Comment by brianjo** [comment]
@rohan-varma Could rebase this? I'll merge it as soon as it passes tests.

**Comment by rohan-varma** [comment]
@brianjo I couldn't find the file "distributed_rpc_profiling.rst" in master or in pytorch/release:1.6 anymore - do you or @jlin27 know where it went? Anyways, I added it back in this PR.

**Comment by jlin27** [comment]
It's under the `prototype_source` folder: https://github.com/pytorch/tutorials/tree/master/prototype_source

For the 1.7 release, all tutorials with features marked prototype were added into this folder so that they wouldn't show up on the website. The rationale is that prototype features are based off of unstable code so we didn't want users running across prototype tutorials and expecting them to work based off of stable code. The idea was that once the feature was no longer prototype, it would be "graduated" out of that folder into (into `intermediate_source` or one of the other sources).

**Comment by brianjo** [comment]
OK I'm going to merge this one and remove the prototype file. Thanks @jlin27!

**Pull request merged**
