### PR TITLE
Fix model to be properly exported to ONNX

### PR DESCRIPTION
**Pull request by thiagocrepaldi**
`len()` is a python operator that is not well supported by ONNX during model export.

This PR replaces `len(tensor)` by `tensor.size(0)` to ensure proper model export to ONNX, as this model is stateful and by using `len` will cause it to be static assigned a dimension instead of dynamic

### CODE REVIEW

**Comment by thiagocrepaldi** [comment]
cheers @zhangguanheng66 is there anything else I should do to get this PR merged? This is my first PR on the tutorials repo

**Comment by zhangguanheng66** [comment]
> cheers @zhangguanheng66 is there anything else I should do to get this PR merged? This is my first PR on the tutorials repo

Could you rebase with the master branch? @brianjo will be able to merge it.

**Comment by brianjo** [comment]
> > cheers @zhangguanheng66 is there anything else I should do to get this PR merged? This is my first PR on the tutorials repo
> 
> Could you rebase with the master branch? @brianjo will be able to merge it.

I can rebase automatically. I'll merge it on test pass. Thanks!

**Comment by thiagocrepaldi** [comment]
> > > cheers @zhangguanheng66 is there anything else I should do to get this PR merged? This is my first PR on the tutorials repo
> > 
> > 
> > Could you rebase with the master branch? @brianjo will be able to merge it.
> 
> I can rebase automatically. I'll merge it on test pass. Thanks!

Thank you @brianjo . It seems all tests have passed :)

**Pull request merged**
