### PR TITLE
Add saved tensors hooks tutorial

### PR DESCRIPTION
**Pull request by Varal7**
Add tutorial for saved tensors hooks, also see 

Docs in autograd notes: https://github.com/pytorch/pytorch/pull/62362
Docstrings in torch.autograd: https://pytorch.org/docs/master/autograd.html#saved-tensors-default-hooks

Preview for this PR: https://deploy-preview-1655--pytorch-tutorials-preview.netlify.app/intermediate/autograd_saved_tensors_hooks

### CODE REVIEW

**Comment by Varal7** [comment]
Figure I actually want to use:

**Review by albanD — APPROVED** [review]
LGTM

**Comment by brianjo** [comment]
Currently seeing this error in the build after rebasing on 1.10. 

```
Oct 20 20:49:00 
Oct 20 20:49:00 Exception occurred:
Oct 20 20:49:00   File "/opt/conda/lib/python3.6/site-packages/sphinx_gallery/gen_gallery.py", line 512, in summarize_failing_examples
Oct 20 20:49:00     "\n" + "-" * 79)
Oct 20 20:49:00 ValueError: Here is a summary of the problems encountered when running the examples
Oct 20 20:49:00 
Oct 20 20:49:00 Unexpected failing examples:
Oct 20 20:49:00 /var/lib/jenkins/workspace/intermediate_source/autograd_saved_tensors_hooks_tutorial.py failed leaving traceback:
Oct 20 20:49:00 Traceback (most recent call last):
Oct 20 20:49:00   File "/opt/conda/lib/python3.6/site-packages/sphinx_gallery/gen_rst.py", line 394, in _memory_usage
Oct 20 20:49:00     out = func()
Oct 20 20:49:00   File "/opt/conda/lib/python3.6/site-packages/sphinx_gallery/gen_rst.py", line 382, in __call__
Oct 20 20:49:00     exec(self.code, self.globals)
Oct 20 20:49:00   File "/var/lib/jenkins/workspace/intermediate_source/autograd_saved_tensors_hooks_tutorial.py", line 178, in <module>
Oct 20 20:49:00     with torch.autograd.graph.saved_tensors_hooks(pack_hook, unpack_hook):
Oct 20 20:49:00 AttributeError: module 'torch.autograd' has no attribute 'graph'
Oct 20 20:49:00 
```

**Comment by brianjo** [comment]
> This is weird, it runs just fine locally. Rebased an pushed again to see if it helps

Hey this was set against the wrong branch. Rebasing against master.

**Comment by albanD** [comment]
Thanks. All the CI is green now. So should be ready to merge once CI is done.

**Pull request merged**
