### PR TITLE
fix confusion w.r.t. which model to serialize and use in cpp_export tutorial

### PR DESCRIPTION
**Pull request by Krovatkin**
Addressing feedback we got from @SethHWeidman .
Mainly, making sure there's no confusion which serialized model should be loaded in a c++ app.

### CODE REVIEW

**Comment by Krovatkin** [comment]
@brianjo would it be possible to merge a small update to this tutorial?

@SethHWeidman gave it a try and, unfortunately, it wasn't as clear as we would've hoped 😢

**Comment by SethHWeidman** [comment]
Appreciate you making these changes @Krovatkin.

Could I request one more change? In the line near the end of the tutorial:

```
root@4b5a67132e81:/example-app/build# ./example-app model.pt
```

Could we change this to:

```
root@4b5a67132e81:/example-app/build# ./example-app traced_resnet_model.pt
```

Part of my confusion in going through this tutorial was that the `example-app` we have only works with the ResNet model since we are passing in a 4D Tensor, so if someone tries to run this with `custom_model.pt`, they'll get a confusing error.

Adding a note to this effect - that we are pushing a 4D Tensor through our model here, so this `example-app` will only work with a CNN model - would be even better 🙂

**Comment by Krovatkin** [comment]
> Could we change this to:

Arrgh, I thought `example.cpp` was supposed to use `MyModule.` Fixed it.

**Comment by brianjo** [comment]
I'll merge this after it rebases. Thanks!

**Comment by SethHWeidman** [comment]
Hey @Krovatkin, don't mean to be a pest about this, but I meant the very last time we call `example-app`, where it prints a slice of the first five elements of the result of feeding the Tensor through the model. It still says 

`root@4b5a67132e81:/example-app/build# ./example-app model.pt` 

Could we change that line to:

`root@4b5a67132e81:/example-app/build# ./example-app <path_to_model>/traced_resnet_model.pt` 

Or Brian or I can change directly on `master` after this merges. Thanks!

**Comment by Krovatkin** [comment]
@SethHWeidman ah, you meant the output of a CMake script. Nice catch! Thanks for the update!

**Pull request merged**
