### PR TITLE
rename translation_transformer tutorial (#1612)

### PR DESCRIPTION
**Pull request by 9bow**
### Related Issue

rename translation_transformer tutorial to build with gallery (#1612)

### What would change

[beginner/translation_transformer](https://github.com/pytorch/tutorials/blob/master/beginner_source/translation_transformer.py) tutorial(#1564) is awesome but by [default setting in conf.py](https://github.com/pytorch/tutorials/blob/master/conf.py#L71) it does not build gallery.

So I renamed the tutorial's name from `translation_transformer.py` to `translation_transformer_tutorials.py` to build gallery with default sphinx conf.

I also fixed filename referenced by index.rst respectively.

### CODE REVIEW

**Comment by 9bow** [comment]
I checked this works using Korean-translated tutorial, but need to double check on this official tutorial.
So I'll check built result and report if something is not work as expected.

**Comment by 9bow** [comment]
How do I found `make docs` result about this PR?
I checked [the netlify preview](https://deploy-preview-1616--pytorch-tutorials-preview.netlify.app/), but it seems like results of `make html-noplot` instead of `make docs`. (Anyway the changes on `index.rst` works well.)

Is there any way to find `full`(= `make docs`) PR build result?

**Comment by parmeet** [comment]
cc: @brianjo

**Comment by 9bow** [comment]
Thanks, @parmeet :)

**Comment by 9bow** [comment]
Hi, @branjo 
Could you take a look about this?

**Comment by brianjo** [comment]
> How do I found `make docs` result about this PR? I checked [the netlify preview](https://deploy-preview-1616--pytorch-tutorials-preview.netlify.app/), but it seems like results of `make html-noplot` instead of `make docs`. (Anyway the changes on `index.rst` works well.)
> 
> Is there any way to find `full`(= `make docs`) PR build result?

Since it takes hours to build this on a single machine, we usually suggest people run the file locally and watch the output in their console. I have a stripped down tutorial project you can fork and copy a file into to test it if you want to see the output. There's some information in the readme.  https://github.com/brianjo/pttutorialtest

**Comment by svekars** [comment]
@9bow thank you for submitting this PR. It looks like it cannot be merged in this state, so I'll have to close it. You can resubmit once again.

**Comment by 9bow** [comment]
Thanks for letting me know, @svekars 😄

**Pull request closed without merging**
