### PR TITLE
Describe how to put inputs on GPU in Deep Learning tutorial

### PR DESCRIPTION
**Pull request by gojira**
Per discussion in Issues, adding a note on how to put the inputs on GPU.

Made as small a change a possible as opposed to adding a new executable cell etc.

### CODE REVIEW

**Comment by apaszke** [comment]
Can you add that to a code cell, not as markdown?

**Comment by gojira** [comment]
Do you want JUST that line or the full training block?

**Comment by apaszke** [comment]
Ah I see now, nevermind. Can you change the description a bit? To something more like "Remember that you'll have to send the inputs and targets at every step to the GPU too: <code here>".

**Comment by gojira** [comment]
OK, updated as suggested

**Comment by gojira** [comment]
No action so closing

**Comment by apaszke** [comment]
Sorry, I must have read a notification about your update on the go, and forgot to merge them. Thanks!

**Pull request merged**
