### PR TITLE
[WIP][CheatSheet] update out of place ops, update act fn, optimzers, schedulers, samplers

### PR DESCRIPTION
**Pull request by ptrblck**
Added some update to out-of-place tensor operations as well as some updates to
* activation functions
* optimizers
* schedulers
* samplers

CC @jspisak 

Let me know, if these changes look OK and I can add them to the `PyTorch Cheat.md`.
Tagging this PR as WIP for now.

### CODE REVIEW

**Comment by ptrblck** [comment]
Could it be failing, because I would need to add the same changes to this file: https://github.com/pytorch/tutorials/blob/master/beginner_source/PyTorch%20Cheat.md ?

**Comment by ptrblck** [comment]
If the changes look OK, I'll add the same diffs to the other mentioned file later tonight.

**Comment by jspisak** [comment]
yes, we should actually be updating the .md file which is then renders the .rts. Thanks!

**Comment by jlin27** [comment]
Let me look into the Netlify builds. I cleared the cache and rebuild which usually clears it up. 

Thanks @ptrblck for these updates!

**Comment by ptrblck** [comment]
@jlin27 Thanks for looking into it!
I'm not sure why there are two files, but I saw that both seem to have commits.
I've just updated one file and can update the other one in a follow-up PR, if necessary.

**Pull request merged**
