### PR TITLE
Rollback ddp tutorial fix

### PR DESCRIPTION
**Pull request by bowangbj**
Subsume: https://github.com/pytorch/tutorials/pull/1621

Context: https://github.com/pytorch/tutorials/pull/1621 base branch was messed up due to use of ghstack tool.

### CODE REVIEW

**Comment by bowangbj** [comment]
Hey Shen, Brian -- this is follow up of https://github.com/pytorch/tutorials/pull/1621 
This PR will subsume it since before I was using ghstack which messed up the base branch. Please review this one instead.

**Comment by brianjo** [comment]
@bowangbj Do we still need to land this? If so, I'll do so after confirm. Thanks!

**Comment by bowangbj** [comment]
> @bowangbj Do we still need to land this? If so, I'll do so after confirm. Thanks!

My hunch is that we still need it. @mrshenli  Shen, can you take a quick review?  Thanks!

**Comment by brianjo** [comment]
Hey, I'm going to close this as I think we took care of it in another PR. If you want to change the file, can you do a new PR? Thanks!

**Pull request closed without merging**
