### PR TITLE
Deleting unused version of nn tutorial

### PR DESCRIPTION
**Pull request by brianjo**

### CODE REVIEW

**Comment by JoelMarcey** [comment]
Gotta find out why the previews are failing. But we can still move forward with this, I think.

**Comment by JoelMarcey** [comment]
Gotta find out why the previews are failing. But we can still move forward with this, I think.

**Comment by JoelMarcey** [comment]
@brianjo Does anything need to be changed in the .rst ToC as well to remove this?

**Comment by brianjo** [comment]
No, this was just in there for testing. Thanks.

**Pull request merged**
