### PR TITLE
update CXX compiler from 11 to 14

### PR DESCRIPTION
**Pull request by lzxzy**
According to [31037](https://github.com/pytorch/pytorch/issues/31037)

### CODE REVIEW

**Comment by peterjc123** [comment]
cc @soumith

**Comment by soumith** [comment]
cc: @yf225 @smessmer 

I am not sure if I should merge this right now, or wait for the 14 transition to finish

**Comment by holly1238** [comment]
Hi @lzxzy! Can you sign the CLA agreement so that I can merge the pull request? Thanks!

**Comment by lzxzy** [comment]
Sure, thanks for your remind. I have signed the CLA just now.

holly1238 ***@***.***> 于2021年4月17日周六 上午6:16写道：

**Pull request merged**
