### PR TITLE
Modifying data_parallel_tutorial.py to enable multiple GPU support

### LINKED ISSUE #2563: Multiple GPU example limited to one GPU
https://github.com/pytorch/tutorials/blob/646c8b6368e4f43acc808e0ddddc569153d6a30f/beginner_source/blitz/data_parallel_tutorial.py#L60

Isn't this line limiting the example to **one** GPU no matter how many GPUs are available?

cc @sekyondaMeta @svekars @carljparker @NicolasHug @kit1980 @subramen

### PR DESCRIPTION
**Pull request by prithviraj-maurya**
Fixes #2563

## Description
Modifying data_parallel_tutorial.py, by removing the specification "cuda:0," you enable the use of multiple GPUs. When you specify the index "0," it restricts the computation to only the GPU at index 0. However, if your system has multiple GPUs available, PyTorch will automatically distribute the computation across all available GPUs, resulting in faster training for deep learning tasks. This flexibility allows you to take full advantage of your GPU resources and potentially reduce training times when working with multiple GPUs.

## Checklist

- [x] The issue that is being fixed is referred in the description (see above "Fixes #ISSUE_NUMBER")
- [x] Only one issue is addressed in this pull request
- [x] Labels from the issue that this PR is fixing are added to this pull request
- [x] No unnecessary issues are included into this pull request.

cc @sekyondaMeta @svekars @carljparker @NicolasHug @kit1980 @subramen

### CODE REVIEW

**Review by malfet — CHANGES_REQUESTED** [review]
Can you please modify the PR title to clearly describe what are you trying to achieve there?

**Comment by prithviraj-maurya** [comment]
@malfet  I have updated the title to reflect the task, do let me know if that looks good?

**Comment by malfet** [comment]
@prithviraj-maurya can you explain in a bit more detail how it enables multiple GPU support? (reading thru a tutorial code now)

**Comment by prithviraj-maurya** [comment]
@malfet I have updated the description of PR.

**Comment by malfet** [comment]
When I run original code of the tutorial on multi-gpu system, I see it's already allocating memory on multiple GPU, so I'm not sure where the notion that replacing "cuda:0", with "cuda" would have any effect is coming from

**Comment by prithviraj-maurya** [comment]
@malfet Ah, I see that now. Do you think this change might not be needed then? The original issue talked about changes required on that code.

**Comment by svekars** [comment]
We need to close this as we found out that the changes are not needed per @malfet. Will grant half credit for the issue.

**Pull request closed without merging**
