### PR TITLE
Added cache for incremental build.

### PR DESCRIPTION
**Pull request by v-jizhang**
Added cache for incremental build.

### CODE REVIEW

**Comment by v-jizhang** [comment]
Fix for #1108

**Review by seemethere — COMMENTED** [review]
This looks mostly okay, but wouldn't this only save the cache for the current PR / job?

Like, from my overview, it seems to me that the first runs would take exactly the same amount of time as it currently takes. Only subsequent runs would actually benefit from this cache.

**Comment by v-jizhang** [comment]
> This looks mostly okay, but wouldn't this only save the cache for the current PR / job?
> 
> Like, from my overview, it seems to me that the first runs would take exactly the same amount of time as it currently takes. Only subsequent runs would actually benefit from this cache.

Ii caches for master branch too. And yes, the first time run does not have cache to use and subsequent run benefit for the cache.

**Comment by brianjo** [comment]
I'm thinking about merging this if we pass tests. Could reviewers chime in on it?

**Review by ranman — APPROVED** [review]

**Pull request merged**
