### PR TITLE
remove unused imports and optimizer code in saving and loading models recipe

### PR DESCRIPTION
**Pull request by dineshladi**
- removed `torch.optim` import and added `torch.nn.functional` import
- removed unused optimizer creation code

### CODE REVIEW

**Comment by dineshladi** [comment]
@msaroufim could you please review this PR.

**Comment by dineshladi** [comment]
@svekars, could you review this PR.

**Comment by dineshladi** [comment]
@msaroufim could you please review this PR

**Comment by svekars** [comment]
Closing this as we never heard back from the author. Feel free to reopen with more context if needed.

**Pull request closed without merging**
