### PR TITLE
Update layout.html

### PR DESCRIPTION
**Pull request by brianjo**
Collapses most sections by default.

### CODE REVIEW

**Comment by brianjo** [comment]
@Bgreen23 Hey Brandon, can you take a look at this PR and let me know if I'm doing anything wrong? Thanks!

**Comment by Bgreen23** [comment]
> @Bgreen23 Hey Brandon, can you take a look at this PR and let me know if I'm doing anything wrong? Thanks!

You did everything correctly, the issue was on my end. There was an errant `collapsedSection` array left in the previous theme PR used to generate the preview that was overriding the array you put together. I opened this [PR](https://github.com/pytorch/pytorch_sphinx_theme/pull/100) to remove that array

**Comment by brianjo** [comment]
> > @Bgreen23 Hey Brandon, can you take a look at this PR and let me know if I'm doing anything wrong? Thanks!
> 
> @brianjo You did everything correctly, the issue was on my end. There was an errant `collapsedSection` array left in the previous theme PR used to generate the preview that was overriding the array you put together. I opened this [PR](https://github.com/pytorch/pytorch_sphinx_theme/pull/100) to remove that array

Great. Thanks!

**Comment by brianjo** [comment]
@Bgreen23 Looks like their might be an issue with having that / character in 'Image/Video'. Looking at the preview, everything but that is collapsed. (No need to worry about that tonight. I'll figure out if escaping it will work tomorrow.) Thanks! 

https://deploy-preview-1389--pytorch-tutorials-preview.netlify.app

**Pull request merged**
