### PR TITLE
Update parallelism_tutorial.py

### PR DESCRIPTION
**Pull request by keunwoochoi**
Regarding https://github.com/pytorch/pytorch/issues/16885 .

### CODE REVIEW

**Comment by soumith** [comment]
thanks @keunwoochoi !

**Comment by keunwoochoi** [comment]
😊👍

**Comment by wangg12** [comment]
@keunwoochoi I got an error by adding this method:
```
    return getattr(self.module, name)
  [Previous line repeated 329 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
```
What is the correct way of accessing the updated module attributes?

**Comment by keunwoochoi** [comment]
@wangg12 Alright, not sure if it's related but could you try this?
```python
class OpenDataParallel(nn.DataParallel):
    """custom class so that I can have other attributes than modules."""

    def __init__(self, module, **kwargs):
        super(OpenDataParallel, self).__init__(module, **kwargs)

    def __getattr__(self, name):
        if name is not 'module':
            try:
                return getattr(self.module, name)
            except AttributeError:
                pass

        return super(nn.DataParallel, self).__getattr__(name)


```

**Pull request merged**
