### PR TITLE
Remove broken links in tuning guide

### LINKED ISSUE #2629: [BUG] broken links in tuning_guide.html
### Add Link

https://pytorch.org/tutorials/recipes/recipes/tuning_guide.html

### Describe the bug

1 broken link in 2 places:
```
More detailed descriptions can be found `here <https://software.intel.com/content/www/us/en/develop/articles/how-to-get-better-performance-on-pytorchcaffe2-with-intel-acceleration.html>`_.

Detailed information can be found `here <https://software.intel.com/content/www/us/en/develop/articles/how-to-get-better-performance-on-pytorchcaffe2-with-intel-acceleration.html>`_.
```

in https://github.com/pytorch/tutorials/blob/main/recipes_source/recipes/tuning_guide.py

I couldn't find the original. 

When linking to company websites like Intel's it might be a good idea to first save the page in https://web.archive.org/ and link there as wikipedia does. It's almost guaranteed a newly hired designer is going to 404 many links at least once a year.

Thank you.

cc @svekars @carljparker @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @ZailiWang @ZhaoqiongZ @leslie-fang-intel @Xia-Weiwen @sekahler2 @CaoE @zhuhaozhe @Valentine233 @sekyondaMeta @NicolasHug @kit1980 @subramen

### PR DESCRIPTION
**Pull request by markstur**
A couple of "for more details" links to external sites are no longer finding details. Better to remove them.

Fixes #2629 

## Description
The current suggestion was to remove the links.  It is better to not suggest more details when the links destinations move.

## Checklist

- [x] The issue that is being fixed is referred in the description (see above "Fixes #ISSUE_NUMBER")
- [x] Only one issue is addressed in this pull request
- [x] Labels from the issue that this PR is fixing are added to this pull request
- [x] No unnecessary issues are included into this pull request.

cc @svekars @carljparker @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @ZailiWang @ZhaoqiongZ @leslie-fang-intel @Xia-Weiwen @sekahler2 @CaoE @zhuhaozhe @Valentine233 @sekyondaMeta @NicolasHug @kit1980 @subramen

### CODE REVIEW

**Review by svekars — APPROVED** [review]
Thanks!

**Comment by svekars** [comment]
@derrickmo it's okay but you don't really need to assign the pull request to yourself. Just the issues.

**Comment by derrickmo** [comment]
Got it. Thanks for the note. I will look into other issues 👍

**Comment by markstur** [comment]
looks good in the CI built preview https://docs-preview.pytorch.org/pytorch/tutorials/2636/recipes/recipes/tuning_guide.html

**Pull request merged**
