### PR TITLE
Updates to accommodate torchtext related changes

### PR DESCRIPTION
**Pull request by parmeet**
This PR takes care of the changes introduced in upcoming release (0.10.0) of torchtext library.

### CODE REVIEW

**Review by pritamdamania87 — COMMENTED** [review]
Changes look good to me, I'm assuming both pipeline tutorials have been verified to work by running them?

**Comment by parmeet** [comment]
> Changes look good to me, I'm assuming both pipeline tutorials have been verified to work by running them?

Unfortunately, I do not have access to multi-GPU platform yet. So I haven't run them :( .

**Comment by parmeet** [comment]
@brianjo This one also requires pytorch and torchtext RC

**Review by brianjo — COMMENTED** [review]
Hey @parmeet, can you take a look at the output here: https://app.circleci.com/pipelines/github/pytorch/tutorials/4461/workflows/f37496d7-3ac7-43ab-bea1-47292f2823d6/jobs/85483. There may be a bug, or I may not have the test branch working correctly on this one.  Thanks!

**Comment by parmeet** [comment]
> Hey @parmeet, can you take a look at the output here: https://app.circleci.com/pipelines/github/pytorch/tutorials/4461/workflows/f37496d7-3ac7-43ab-bea1-47292f2823d6/jobs/85483. There may be a bug, or I may not have the test branch working correctly on this one. Thanks!

Hey @brianjo Right, this is the issue coming from torchtext. We have same issue on the other PR https://app.circleci.com/pipelines/github/pytorch/tutorials/4454/workflows/3e100b56-16b6-4364-9120-65903f99102a/jobs/85441 . My guess is the rc version for torchtext  (https://github.com/pytorch/text/pull/1315) is not getting installed here as dependency?

**Comment by parmeet** [comment]
closing due to rebasing issues

**Pull request closed without merging**
