### PR TITLE
Flask tutorial

### PR DESCRIPTION
**Pull request by SethHWeidman**
Just went through this tutorial, had a couple annoying pain points that I tried to address here:

- Made it more clear that students will have to adjust the file paths to point to where the files are located on their machines.
- Changed hitting the app via `curl` to hitting it via `requests`. I had issues getting `curl` to play nicely with Flask - also, starting to use `requests` will set the students up to do more sophisticated things during the hack-a-thon.

### CODE REVIEW

**Comment by jspisak** [comment]
cc @jeffreyksmithjr

**Comment by soumith** [comment]
changes look good to me, but you seem to have updated the sphinx theme git submodule in this PR

**Comment by SethHWeidman** [comment]
Yep @soumith, *just* figured out how to fix that 👍

**Comment by jeffreyksmithjr** [comment]
Amazing stuff. Thanks for improving this tutorial, @SethHWeidman .

**Pull request merged**
