### PR TITLE
some improvements to the make download(#384)

### PR DESCRIPTION
**Pull request by 9bow**
I've made the following improvements in `download`:

1. Changed all `curl` commands to `wget`.
2. Use all `wget` commands with the `-N` option. Therefore, download and compare the timestamp.
3. All downloaded files are located in the `$(DATADIR)` directory (using `-P` option).
4. A redirect to a null file(`>null`) has been replaced by the `-q` (quiet) option to `unzip`.
5. Removed `sudo` / `chmod`.
6. Unused directories (eg. `data`) have been deleted.

Please review this PR.
Thanks.

### CODE REVIEW

**Comment by 9bow** [comment]
Here's the `diff` result of file/dir lists(using `ls -alFRh`) after `make download` command.
(The changes described above applied.)

```
2c2
< total 108K
---
> total 7.3G
4a5
> -rw-rw-r--  1 ubuntu ubuntu 246M Sep 17 15:16 4000_checkpoint.tar
10a12
> -rw-rw-r--  1 ubuntu ubuntu 9.5M Dec 19 05:21 cornell_movie_dialogs_corpus.zip
12c14,16
< drwxrwxr-x  2 ubuntu ubuntu 4.0K Dec 19 05:35 _data/
---
> drwxrwxr-x  2 ubuntu ubuntu 4.0K Dec 19 05:21 data/
> -rw-rw-r--  1 ubuntu ubuntu 2.8M Mar 15  2017 data.zip
> -rw-rw-r--  1 ubuntu ubuntu 5.6M Jun 10  2017 faces.zip
14a19,20
> -rw-rw-r--  1 ubuntu ubuntu  46M Mar 15  2017 hymenoptera_data.zip
> -rw-rw-r--  1 ubuntu ubuntu 1.4G Dec 19 05:21 img_align_celeba.zip
19c25,26
< -rw-rw-r--  1 ubuntu ubuntu 3.8K Dec 19 05:16 Makefile
---
> -rw-rw-r--  1 ubuntu ubuntu 3.2K Dec 19 05:16 Makefile
> -rw-rw-r--  1 ubuntu ubuntu 1.2K Dec 19 05:21 null
25a33
> -rw-rw-r--  1 ubuntu ubuntu 5.7G Dec 19 05:34 UrbanSound8K.tar.gz
113c121
< drwxrwxr-x  3 ubuntu ubuntu 4.0K Dec 19 05:21 celeba/
---
> drwxrwxrwx  3 root   root   4.0K Dec 19 05:21 celeba/
124c132
< drwxrwxr-x 3 ubuntu ubuntu 4.0K Dec 19 05:21 ./
---
> drwxrwxrwx 3 root   root   4.0K Dec 19 05:21 ./
131c139
< drwxrwxr-x 3 ubuntu ubuntu 4.0K Dec 19 05:21 ../
---
> drwxrwxrwx 3 root   root   4.0K Dec 19 05:21 ../
203285c203293
< total 420K
---
> total 424K
212160,212162c212168,212170
< ./_data:
< total 7.3G
< drwxrwxr-x  2 ubuntu ubuntu 4.0K Dec 19 05:35 ./
---
> ./data:
> total 8.0K
> drwxrwxr-x  2 ubuntu ubuntu 4.0K Dec 19 05:21 ./
212164,212172d212171
< -rw-rw-r--  1 ubuntu ubuntu 246M Sep 17 15:16 4000_checkpoint.tar
< -rw-rw-r--  1 ubuntu ubuntu 9.5M Aug 15 19:15 cornell_movie_dialogs_corpus.zip
< -rw-rw-r--  1 ubuntu ubuntu 2.8M Mar 15  2017 data.zip
< -rw-rw-r--  1 ubuntu ubuntu 5.6M Jun 10  2017 faces.zip
< -rw-rw-r--  1 ubuntu ubuntu  46M Mar 15  2017 hymenoptera_data.zip
< -rw-rw-r--  1 ubuntu ubuntu 1.4G Aug 15 16:39 img_align_celeba.zip
< -rw-rw-r--  1 ubuntu ubuntu 4.5K Aug 15 16:39 iris.data
< -rw-rw-r--  1 ubuntu ubuntu  87K Aug 15 16:41 lenet_mnist_model.pth
< -rw-rw-r--  1 ubuntu ubuntu 5.7G Aug 15 16:39 UrbanSound8K.tar.gz
212305c212304
< drwxrwxr-x  3 ubuntu ubuntu 4.0K Dec 19 05:17 data/
---
> drwxr-xr-x  3 ubuntu ubuntu 4.0K Mar 12  2017 data/
212314c212313
< drwxrwxr-x 3 ubuntu ubuntu 4.0K Dec 19 05:17 ./
---
> drwxr-xr-x 3 ubuntu ubuntu 4.0K Mar 12  2017 ./
212322c212321
< drwxrwxr-x 3 ubuntu ubuntu 4.0K Dec 19 05:17 ../
---
> drwxr-xr-x 3 ubuntu ubuntu 4.0K Mar 12  2017 ../
```

**Comment by brianjo** [comment]
Hey Junghwan, thanks for your work on this. I'm going to test the build on a local machine and we'll look at merging this next week.

**Comment by 9bow** [comment]
Thanks. Please let me know if any issue occurs while testing. 🤞

**Comment by brianjo** [comment]
Junghwan, I've been having trouble with getting this build to work on my test server. (Not anything in your code, just an issue with my server.) Could you rebase and we'll take a look at the check logs from the PR? I didn't see any issues as far as my build got. Thanks.

**Comment by 9bow** [comment]
Done. I hope there's no problem anymore.
Thanks!

**Comment by 9bow** [comment]
Sorry for missing data dir `_data` in `.gitignore`.
I opened the PR #414 about this.

**Pull request merged**
