### PR TITLE
Update links in RPC tutorial

### PR DESCRIPTION
**Pull request by mrshenli**

### CODE REVIEW

**Comment by mrshenli** [comment]
hey @jlin27 @rohan-varma, I noticed that the url has changed in master compared to stable. 

master: master/rpc/rpc.html
stable: stable/rpc.html

Does this mean we should update all links in tutorial?

**Comment by rohan-varma** [comment]
I think that the difference is `master` will always show the latest docs (i.e. the ones that are landed to master), stable will show the ones corresponding to the current release. Given that we want to release Dist RPC framework as stable, I think we should do this update. cc @jlin27

**Comment by abitrolly** [comment]
Looks like this got stalled because of branch conflict.

**Comment by mrshenli** [comment]
My bad, will create a new one to fix links and also add links to DDP + RPC and autograd profiler.

**Pull request merged**
