### PR TITLE
Fix broken pipe error in cifar10_tutorial.py

### PR DESCRIPTION
**Pull request by krikru**

### CODE REVIEW

**Comment by peterjc123** [comment]
@soumith Should we merge this?

**Comment by soumith** [comment]
@peterjc123 is the issue fixed on pytorch master? we are planning a 0.4.1 release for July 15th, and if it's fixed on master, the fix will be in there.

**Comment by peterjc123** [comment]
@soumith This is not a specific issue for PyTorch. It is just a general problem for Python on Windows. In interactive mode, the multiprocessing can't be used. And good news for a new release.

**Comment by brianjo** [comment]
As we've reorganized and updated a number these tutorials, we're going to close most of the older PRs. If you would like to recreate this PR, please rebase on the latest build. Thanks for our understanding.

**Pull request closed without merging**
