### PR TITLE
Fix assert statements to compare the expected and actual values

### PR DESCRIPTION
**Pull request by bjhargrave**
The original assert statements incorrectly used the second value as the assertion failure message. This means the assert statements always succeeded as long the the object id was not zero.

cc @suraj813

### CODE REVIEW

**Review by suraj813 — APPROVED** [review]
@bjhargrave nice catch, thanks for fixing!

**Comment by svekars** [comment]
@bjhargrave please sign the CLA so we can accept your change. Thanks!

**Comment by bjhargrave** [comment]
> please sign the CLA so we can accept your change. Thanks!

Trying to get the right person in IBM to add me to the CCLA...

**Comment by bjhargrave** [comment]
> Thank you for signing our Contributor License Agreement.

@svekars CLA is finally signed.

**Pull request merged**
