### PR TITLE
Add sphinx notebook tutorials

### PR DESCRIPTION
**Pull request by chsasank**
Creating a PR following discussion at #47 . I've removed my git history.
Old notebooks are deleted. 

**How to build**:
`make docs` will download the data, execute the tutorials and create a html documentation at `docs` folder. This directory should be committed to gh-pages branch at root.

### CODE REVIEW

**Comment by soumith** [comment]
just fyi, you dont need to remove your git history if you think it's useful (upto you)

**Comment by chsasank** [comment]
It's not useful, it's very messy.

**Comment by soumith** [comment]
http://pytorch.github.io/tutorials/

**Comment by chsasank** [comment]
It needs to be built!

**Comment by soumith** [comment]
i've given you commit access to the repo. you are the maintainer after all :)

**Comment by chsasank** [comment]
Is there some chat channel? We still need to discuss how to build a la pytorch/pytorch gh-pages

**Comment by soumith** [comment]
invited you to slack. come onto #tutorials

**Pull request merged**
