### PR TITLE
Fix name error in audio tutorial

### PR DESCRIPTION
**Pull request by vincentqb**
Follow up to #1204

- [x] Rename tutorial as mentioned in #1222
- [x] There is an error in the multiline string.
- [ ] ~~Make notebook run outside of google colab. #1252~~
- [x] Fix tqdm import

cc @brianjo

### CODE REVIEW

**Comment by vincentqb** [comment]
BTW I've also noticed that there's a "SyntaxError" appear on the main page. cc @brianjo 

Screen Shot 2020-11-10 at 5 10 58 PM

**Comment by vincentqb** [comment]
> BTW I've also noticed that there's a "SyntaxError" appear in the menu [here](https://pytorch.org/tutorials/beginner/audio_preprocessing_tutorial.html). cc @brianjo

cc #1236 for this

**Comment by vincentqb** [comment]
Quote from log:
```
Nov 17 22:09:13 -------------------------------------------------------------------------------
Nov 17 22:09:13 
Nov 17 22:09:13 Exception occurred:
Nov 17 22:09:13   File "/opt/conda/lib/python3.6/site-packages/sphinx_gallery/gen_gallery.py", line 512, in summarize_failing_examples
Nov 17 22:09:13     "\n" + "-" * 79)
Nov 17 22:09:13 ValueError: Here is a summary of the problems encountered when running the examples
Nov 17 22:09:13 
Nov 17 22:09:13 Unexpected failing examples:
Nov 17 22:09:13 /var/lib/jenkins/workspace/intermediate_source/speech_command_recognition_with_torchaudio_tutorial.py failed leaving traceback:
Nov 17 22:09:13 Traceback (most recent call last):
Nov 17 22:09:13   File "/opt/conda/lib/python3.6/site-packages/sphinx_gallery/gen_rst.py", line 394, in _memory_usage
Nov 17 22:09:13     out = func()
Nov 17 22:09:13   File "/opt/conda/lib/python3.6/site-packages/sphinx_gallery/gen_rst.py", line 382, in __call__
Nov 17 22:09:13     exec(self.code, self.globals)
Nov 17 22:09:13   File "/var/lib/jenkins/workspace/intermediate_source/speech_command_recognition_with_torchaudio_tutorial.py", line 426, in <module>
Nov 17 22:09:13     with tqdm(total=n_epoch) as pbar:
Nov 17 22:09:13   File "/opt/conda/lib/python3.6/site-packages/tqdm/notebook.py", line 232, in __init__
Nov 17 22:09:13     self.fp, total, self.desc, self.ncols)
Nov 17 22:09:13   File "/opt/conda/lib/python3.6/site-packages/tqdm/notebook.py", line 97, in status_printer
Nov 17 22:09:13     "IProgress not found. Please update jupyter and ipywidgets."
Nov 17 22:09:13 ImportError: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
```

It seems like `from tqdm.notebook import tqdm` is not supported.

**Comment by vincentqb** [comment]
[The test failing in 1](https://app.circleci.com/pipelines/github/pytorch/tutorials/2843/workflows/accf5f51-ac9b-48e6-9a70-a5904b03237f/jobs/49898) appears unrelated
```
Nov 19 21:11:11 
Nov 19 21:11:11 Unexpected failing examples:
Nov 19 21:11:11 /var/lib/jenkins/workspace/beginner_source/nn_tutorial.py failed leaving traceback:
Nov 19 21:11:11 Traceback (most recent call last):
Nov 19 21:11:11   File "/opt/conda/lib/python3.6/site-packages/sphinx_gallery/gen_rst.py", line 394, in _memory_usage
Nov 19 21:11:11     out = func()
Nov 19 21:11:11   File "/opt/conda/lib/python3.6/site-packages/sphinx_gallery/gen_rst.py", line 382, in __call__
Nov 19 21:11:11     exec(self.code, self.globals)
Nov 19 21:11:11   File "/var/lib/jenkins/workspace/beginner_source/nn_tutorial.py", line 65, in <module>
Nov 19 21:11:11     ((x_train, y_train), (x_valid, y_valid), _) = pickle.load(f, encoding="latin-1")
Nov 19 21:11:11   File "/opt/conda/lib/python3.6/gzip.py", line 296, in peek
Nov 19 21:11:11     return self._buffer.peek(n)
Nov 19 21:11:11   File "/opt/conda/lib/python3.6/_compression.py", line 68, in readinto
Nov 19 21:11:11     data = self.read(len(byte_view))
Nov 19 21:11:11   File "/opt/conda/lib/python3.6/gzip.py", line 463, in read
Nov 19 21:11:11     if not self._read_gzip_header():
Nov 19 21:11:11   File "/opt/conda/lib/python3.6/gzip.py", line 411, in _read_gzip_header
Nov 19 21:11:11     raise OSError('Not a gzipped file (%r)' % magic)
Nov 19 21:11:11 OSError: Not a gzipped file (b'<!')
```

**Comment by brianjo** [comment]
> [The test failing in 1](https://app.circleci.com/pipelines/github/pytorch/tutorials/2843/workflows/accf5f51-ac9b-48e6-9a70-a5904b03237f/jobs/49898) appears unrelated
> 
> ```
> Nov 19 21:11:11 
> Nov 19 21:11:11 Unexpected failing examples:
> Nov 19 21:11:11 /var/lib/jenkins/workspace/beginner_source/nn_tutorial.py failed leaving traceback:
> Nov 19 21:11:11 Traceback (most recent call last):
> Nov 19 21:11:11   File "/opt/conda/lib/python3.6/site-packages/sphinx_gallery/gen_rst.py", line 394, in _memory_usage
> Nov 19 21:11:11     out = func()
> Nov 19 21:11:11   File "/opt/conda/lib/python3.6/site-packages/sphinx_gallery/gen_rst.py", line 382, in __call__
> Nov 19 21:11:11     exec(self.code, self.globals)
> Nov 19 21:11:11   File "/var/lib/jenkins/workspace/beginner_source/nn_tutorial.py", line 65, in <module>
> Nov 19 21:11:11     ((x_train, y_train), (x_valid, y_valid), _) = pickle.load(f, encoding="latin-1")
> Nov 19 21:11:11   File "/opt/conda/lib/python3.6/gzip.py", line 296, in peek
> Nov 19 21:11:11     return self._buffer.peek(n)
> Nov 19 21:11:11   File "/opt/conda/lib/python3.6/_compression.py", line 68, in readinto
> Nov 19 21:11:11     data = self.read(len(byte_view))
> Nov 19 21:11:11   File "/opt/conda/lib/python3.6/gzip.py", line 463, in read
> Nov 19 21:11:11     if not self._read_gzip_header():
> Nov 19 21:11:11   File "/opt/conda/lib/python3.6/gzip.py", line 411, in _read_gzip_header
> Nov 19 21:11:11     raise OSError('Not a gzipped file (%r)' % magic)
> Nov 19 21:11:11 OSError: Not a gzipped file (b'<!')
> ```

I'll re-kick that shard.

**Pull request merged**
