### PR TITLE
Fixed torchvision install command in intermediate

### PR DESCRIPTION
**Pull request by 0xBono**
**Before**
```python
$ pip install Flask==1.0.3 torchvision-0.3.0
```
**After**
```python
$ pip install Flask==1.0.3 torchvision==0.3.0
```
Document with wrong install command :(

### CODE REVIEW

**Comment by brianjo** [comment]
@0xBono Thanks for this PR. @fmassa Do we need to specify the version of torchvision here?

**Comment by 0xBono** [comment]
> @0xBono Thanks for this PR. @fmassa Do we need to specify the version of torchvision here?

version doesn't really matter. 
However, there may be users who need to use a specific version, so it would be better to leave it that way 👍

**Comment by 0xBono** [comment]
@fmassa You must be very busy.

**Comment by 0xBono** [comment]
@brianjo Progress is disappointingly slow :(

**Comment by 0xBono** [comment]
I was really disappointed.

**Comment by holly1238** [comment]
Closing this PR. This issue was fixed and merged in https://github.com/pytorch/tutorials/pull/1499.

**Pull request closed without merging**
