### PR TITLE
Correct Custom Module Name

### PR DESCRIPTION
**Pull request by leimao**
The torch extension name should be "lltm_cpp" instead of "lltm".

### CODE REVIEW

**Comment by leimao** [comment]
@zou3519 Could you please review this?

**Comment by zou3519** [comment]
Sorry, I just saw this now. The change LGTM, but it looks like it needs a rebase. @leimao could you rebase your branch please?

**Review by zou3519 — APPROVED** [review]
Thank you @leimao and we are terribly sorry for the delay in review! This LGTM and I will merge whenever the CI finishes and looks good.

**Comment by leimao** [comment]
Thank you very much, @zou3519. It seems that the CI tests in the morning failed somehow (I only changed one string...). I rebased and invoked the CI tests again. Hopefully, this time it will work. Thank you.

**Comment by leimao** [comment]
@zou3519 The CI tests were successful this time.

**Comment by zou3519** [comment]
Merged, thank you @leimao!

**Pull request merged**
