### PR TITLE
Fix Checkpoint in Hyperparameter Tuning

### LINKED ISSUE #2679: [BUG] - Failed to import Checkpoint for hyperparameter tuning tutorial
### Add Link

https://pytorch.org/tutorials/beginner/hyperparameter_tuning_tutorial.html

### Describe the bug

The example in the tutorial and raw Github file fail to run. The tutorial imports Checkpoint from ray.air when the Class is defined inside ray.train.

Documentation: https://docs.ray.io/en/latest/train/api/doc/ray.train.Checkpoint.html#ray.train.Checkpoint

Which throws the following error:

```
ImportError: cannot import name 'Checkpoint' from 'ray.air'
```

### Describe your environment

* Platform: MacOS Ventura 13.4.1, M2
* CUDA: No, MPS
* PyTorch version: 2.1.0

### PR DESCRIPTION
**Pull request by atskae**
Fixes #2679 

## Description

Uses the new `Checkpoint` import path and API in the Ray AI library.

## Checklist

- [x] The issue that is being fixed is referred in the description (see above "Fixes #ISSUE_NUMBER")
- [x] Only one issue is addressed in this pull request
- [ ] Labels from the issue that this PR is fixing are added to this pull request
- [x] No unnecessary issues are included into this pull request.

cc @subramen @albanD

### CODE REVIEW

**Comment by atskae** [comment]
I was able to run this on MacOS, Sonoma:
Screenshot 2024-02-27 at 10 56 27 AM
Screenshot 2024-02-27 at 10 57 00 AM
Screenshot 2024-02-27 at 10 57 11 AM

**Comment by atskae** [comment]
Who should be the reviewers for this PR? @krfricke? @svekars?

**Review by krfricke — DISMISSED** [review]
LGTM other than a few nits

**Comment by atskae** [comment]
Thank you for your comments! I found another place where I forgot to close the data file, and removed the problematic import.

**Comment by atskae** [comment]
@krfricke @svekars Would you know when `pytorch_tutorial_build_manager` is expected to start?

**Comment by svekars** [comment]
There seems to be an [error](https://github.com/pytorch/tutorials/actions/runs/8147786462/job/22314475280?pr=2782#step:8:8755).... - we are also updating ray to 2.9 in this [PR](https://github.com/pytorch/tutorials/pull/2789) so maybe let's have that one pass first, then you can rebase and finish your edits.

**Comment by atskae** [comment]
Oops, I accidentally deleted the branch in my forked repository 😅

**Comment by svekars** [comment]
Alright, we updated ray to 2.7. It looks like there is still an [error](https://github.com/pytorch/tutorials/actions/runs/8177107579/job/22359425780#step:8:9831) in this PR. Can you please take a look @atskae ?

**Comment by atskae** [comment]
@svekars Can you try running CI again? I was able to run the notebook with that fix.

**Comment by svekars** [comment]
@krfricke can we ask for a stamp once again if looks good?

**Comment by atskae** [comment]
Maybe @subramen or @albanD can also take a look?

**Comment by albanD** [comment]
I don't think I know Ray well enough to review this and @krfricke is the right person to review this!

**Review by krfricke — APPROVED** [review]
LGTM!

**Comment by atskae** [comment]
@svekars Would you be able to run CI again?

**Pull request merged**
