### PR TITLE
Update tutorials to use TensorPipeRpcBackendOptions.

### PR DESCRIPTION
**Pull request by pritamdamania87**

### CODE REVIEW

**Review by rohan-varma — APPROVED** [review]
Thanks! I'm assuming we would need @lw's PR for inferring the right type of backend for this to work properly?

**Comment by lw** [comment]
Thanks for doing this! That PR is in https://github.com/pytorch/pytorch/pull/45065, and it's ready for review.

**Comment by pritamdamania87** [comment]
> Thanks! I'm assuming we would need @lw's PR for inferring the right type of backend for this to work properly?

I think this would work without the PR since we've updated the tutorials to use the right options when the default is TensorPipe.

**Comment by mrshenli** [comment]
Can we hold on to this PR for several days. There is a chance we might need to revert default backend to Process Group. @lw is discussing that with @jspisak

**Comment by pritamdamania87** [comment]
Landing this since we decided to go with TensorPipe as the default backend.

**Pull request merged**
