### PR TITLE
Update neural_networks_tutorial.py

### PR DESCRIPTION
**Pull request by brianjo**
Update per wrong kernel_size in tutorial #531

### CODE REVIEW

**Comment by ezyang** [comment]
Looks reasonable-ish? Did it fix the problem?

**Comment by brianjo** [comment]
> Looks reasonable-ish? Did it fix the problem?

No, you can see the log from the build below. https://circleci.com/gh/pytorch/tutorials/8178?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link Seeing an issue with awscli. Thanks!

**Comment by yf225** [comment]
@brianjo We might need to move the installation of `awscli` to sudo (https://stackoverflow.com/questions/43873663/awscli-fails-to-work-no-module-named-awscli/44207096). Could you try to also apply this patch:
```
diff --git a/.jenkins/build.sh b/.jenkins/build.sh
index eaed1d00..5548fb31 100755
--- a/.jenkins/build.sh
+++ b/.jenkins/build.sh
@@ -11,6 +11,9 @@ DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
 sudo apt-get update
 sudo apt-get install -y --no-install-recommends unzip p7zip-full sox libsox-dev libsox-fmt-all rsync
 
+sudo pip3 uninstall awscli
+sudo pip3 install awscli==1.16.35
+
 export PATH=/opt/conda/bin:$PATH
 rm -rf src
 pip install -r $DIR/../requirements.txt
diff --git a/requirements.txt b/requirements.txt
index 7d74d4d8..2037e5e0 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -9,7 +9,6 @@ torch
 torchvision
 PyHamcrest
 bs4
-awscli==1.16.35
 
 # PyTorch Theme
 -e git+git://github.com/pytorch/pytorch_sphinx_theme.git#egg=pytorch_sphinx_theme
```

**Comment by brianjo** [comment]
@yf225 I think we're close. I did the uninstall/install without sudo and it worked. Now seeing this:

```
Jul 17 02:02:17 +++ aws configure set default.s3.multipart_threshold 5120MB
Jul 17 02:02:18 +++ export NUM_WORKERS=20
Jul 17 02:02:18 +++ NUM_WORKERS=20
Jul 17 02:02:18 +++ [[ pytorch_tutorial_build_manager == *worker_* ]]
Jul 17 02:02:18 +++ [[ pytorch_tutorial_build_manager == *manager ]]
Jul 17 02:02:18 +++ make html-noplot
Jul 17 02:02:18 sphinx-build -D plot_gallery=0 -b html  "." "_build/html"
Jul 17 02:02:18 Running Sphinx v1.8.2
Jul 17 02:02:18 
Jul 17 02:02:18 Configuration error:
Jul 17 02:02:18 There is a programmable error in your configuration file:
Jul 17 02:02:18 
Jul 17 02:02:18 Traceback (most recent call last):
Jul 17 02:02:18   File "/opt/conda/lib/python3.7/site-packages/sphinx/config.py", line 368, in eval_config_file
Jul 17 02:02:18     execfile_(filename, namespace)
Jul 17 02:02:18   File "/opt/conda/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
Jul 17 02:02:18     exec_(code, _globals)
Jul 17 02:02:18   File "/var/lib/jenkins/workspace/conf.py", line 24, in <module>
Jul 17 02:02:18     import torch
Jul 17 02:02:18 ModuleNotFoundError: No module named 'torch'
Jul 17 02:02:18 
Jul 17 02:02:18 Makefile:92: recipe for target 'html-noplot' failed
Jul 17 02:02:18 make: *** [html-noplot] Error 2
Exited with code 2
```

**Comment by yf225** [comment]
@brianjo Thanks so much for working on it. Based on the CI I think we are seeing:
```
Jul 17 02:00:29 +++ python /var/lib/jenkins/workspace/.jenkins/remove_runnable_code.py beginner_source/audio_classifier_tutorial.py beginner_source/audio_classifier_tutorial.py
Jul 17 02:00:29 Traceback (most recent call last):
Jul 17 02:00:29   File "/var/lib/jenkins/workspace/.jenkins/remove_runnable_code.py", line 10, in <module>
Jul 17 02:00:29     with open(python_file_path, 'r', encoding='utf-8') as file:
Jul 17 02:00:29 FileNotFoundError: [Errno 2] No such file or directory: 'beginner_source/audio_classifier_tutorial.py'
```
And I think the fix is to append `|| true` at the end of these two lines in `.jenkins/build.sh`:
1. `python $DIR/remove_runnable_code.py beginner_source/aws_distributed_training_tutorial.py beginner_source/aws_distributed_training_tutorial.py`
2. `python $DIR/remove_runnable_code.py beginner_source/audio_classifier_tutorial.py beginner_source/audio_classifier_tutorial.py`

**Comment by brianjo** [comment]
Fixed build in another PR. Closing this and doing the original fix in https://github.com/pytorch/tutorials/pull/571.

**Pull request closed without merging**
