### PR TITLE
Minor fixes in tutorial on basics (file names, spaces, links)

### PR DESCRIPTION
**Pull request by fzalkow**
First of all, many thanks for the great tutorial on PyTorch basics, which makes it really easy to get started! While working through the tutorial, I found a couple of minor issues, which I fixed.

* typos in filenames (`tensorqs_tutorial`, `autogradqs_tutorial`)
* a few missing spaces
* a dead link to the documentation of `torch.Tensor.scatter_`

### CODE REVIEW

**Comment by holly1238** [comment]
Hi @fzalkow! The filenames, tensorqs_tutorial and autogradqs_tutorial, are correct (see files in https://github.com/pytorch/tutorials/tree/master/beginner_source/basics). If you remove those changes from the PR, I can merge the rest of your updates. Thanks!

**Comment by fzalkow** [comment]
Hi @holly1238,

Many thanks for your response. I can remove those changes from the PR, but please let us clarify that there is no misunderstanding.

I did not mean that the filenames tensorqs_tutorial and autogradqs_tutorial had wrong links. I meant that there is a typo in the filenames (q in both files). As a user of the tutorial, I downloaded the notebooks and was confused bout the misspelled filenames. That is why in my PR, I **(1.)** renamed the files and **(2.)** changed all links to these files.

Should I really remove the changes 07a339ece661a2b304b8834780470f522eed1e02 (tensorqs_tutorial -> tensors_tutorial) and f0c392906a9e2a3531d40cbd2d799a42e377484e (autogradqs_tutorial -> autograds_tutorial) from the PR? That means you want to keep the misspelled filenames.

**Comment by holly1238** [comment]
Hi @fzalkow! Sorry for not being super clear before! The file names are intentionally tensorqs_tutorial and autogradqs_tutorial. Think of it like tensorqs_tutorial -> tensor quickstart tutorial. We have a handful of tutorials similarly named and the 'qs' signifies to us that they are the tensor and autograd tutorials from the Learn the Basics series (distinct filenames like this helps with things like getting accurate page statistics).

**Comment by fzalkow** [comment]
Oh, I wasn't aware that "qs" means "quick start." Thanks for the clarification! I've undone everything related to the file renaming.

**Pull request merged**
