### PR TITLE
Redo rank --> trainer_rank doc fix

### PR DESCRIPTION
**Pull request by bowangbj**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #1623
* #1621

Summary:

Context: https://github.com/pytorch/tutorials/pull/1619
1619 was merged into a wrong branch (non-master)
Example code fix: pytorch/examples#924

Test Plan:

Reviewers:

Subscribers:

Tasks:

Tags:

### CODE REVIEW

**Comment by bowangbj** [comment]
Hey Yi, Pritam, https://github.com/pytorch/tutorials/pull/1619 was merged to a wrong place. Resent so that we can merge to master. PTAL

**Review by SciPioneer — APPROVED** [review]
Thanks for the fix!

**Comment by bowangbj** [comment]
Thanks Yi for the super quick review. 

Brian, the PR is ready to merge to tutorials, can you help to merge? Thanks

**Review by SciPioneer — APPROVED** [review]

**Comment by brianjo** [comment]
> Thanks Yi for the super quick review.
> 
> Brian, the PR is ready to merge to tutorials, can you help to merge? Thanks

I changed the base to master so i could pull it in. That's what you would like, correct? (It needs to pass tests before I merge it.) Thanks!

**Comment by bowangbj** [comment]
> > Thanks Yi for the super quick review.
> > Brian, the PR is ready to merge to tutorials, can you help to merge? Thanks
> 
> I changed the base to master so i could pull it in. That's what you would like, correct? (It needs to pass tests before I merge it.) Thanks!

For some reason, after changing the base branch, the diffs are changed as well. Original diff only include one file, now it added two additional files. Maybe that's caused by the ghstack tool? Should I redo the diff in a clean branch w/o using ghstack?

**Comment by bowangbj** [comment]
> > > Thanks Yi for the super quick review.
> > > Brian, the PR is ready to merge to tutorials, can you help to merge? Thanks
> > 
> > 
> > I changed the base to master so i could pull it in. That's what you would like, correct? (It needs to pass tests before I merge it.) Thanks!
> 
> For some reason, after changing the base branch, the diffs are changed as well. Original diff only include one file, now it added two additional files. Maybe that's caused by the ghstack tool? Should I redo the diff in a clean branch w/o using ghstack?

As expected, ghstack was not quite good fit for pure OSS flow. 
Did some cleanup and start a new PR https://github.com/pytorch/tutorials/pull/1640
Also add some notes: https://fb.quip.com/BbnDABnsbFn7 for what I've learned during this exercise.

**Comment by bowangbj** [comment]
pls review https://github.com/pytorch/tutorials/pull/1640 instead, closing this PR

**Pull request closed without merging**
