### PR TITLE
Exclude audio_preprocessing_tutorial.py on Windows CI build

### PR DESCRIPTION
**Pull request by skyline75489**

### CODE REVIEW

**Comment by brianjo** [comment]
Hey Chester, thanks for the PR. I've rebased and let's see if all of this works.

**Comment by skyline75489** [comment]
Seems like there's a new failure "Key already registered with the same priority: GroupSpatialSoftmax". I'll talk to @guyang3532 about it and see if I fix it here.

**Comment by skyline75489** [comment]
@brianjo The "Key already registered with the same priority: GroupSpatialSoftmax" failure was caused by installing *both* the CPU and GPU version of torch on Windows. I've fixed that in this PR 😃

**Comment by brianjo** [comment]
This looks like it's working. I'm going to go ahead and merge it. Thanks so much for your work on it.

**Pull request merged**
