### PR TITLE
Tensorboard tutorial

### PR DESCRIPTION
**Pull request by SethHWeidman**
Adding TensorBoard tutorial off of a new fork.

### CODE REVIEW

**Comment by brianjo** [comment]
Let's see how it goes. :)

**Comment by brianjo** [comment]
Don't merge until after I merge the audio tutorial. Thanks!

**Comment by brianjo** [comment]
This is close. Looks like it's just spinning on something in your tutorial.

**Comment by SethHWeidman** [comment]
@brianjo recreated the tutorial as an `.rst`, it now passes all checks. This was never intended to be a tutorial whose code runs and produces output, so we should have created it this way from the start. Ok to merge?

**Pull request merged**
