### PR TITLE
Use the correct batch values in the output

### PR DESCRIPTION
**Pull request by spzala**
The current logic uses enumerate counter (i.e. variable `batch`). It displays the loss for trained data in an increment of 100 using `if batch % 100 == 0`. i.e. 1st batch, 101 stbatch, and so on for the given dataset. This maps to batch =0, 100, and so on). So for the first batch, the loss displayed should be `[ 64/60000]` instead of `[ 0/60000]`. For the second it should be `[ 6464/60000]` instead of `[ 6400/60000]` , and so on. The values displayed in the `Out:` text box on the tutorial page, e.g. `loss: 2.306185  [ 0/60000]`, read as a loss observed for zero input data which seems incorrect. This loss mentioned here was for the first batch, which was 64 input data. The second was for 101 batch which has 6464 input data, and so on.

cc @suraj813

### CODE REVIEW

**Comment by spzala** [comment]
@svekars thanks! The other thing I want to mention is that I couldn’t find a way to update the  values in the `Out:` box on the tutorial page, I hope you can help there :) If the PR pass the review, here are the values that should be used in all the epoch. We can leave the `loss` value as such considering this is an example and the values will be different in different user environment. 
```
[   64/60000]
[ 6464/60000]
[12864/60000]
[19264/60000]
[32064/60000]
[25664/60000]
[38464/60000]
[44864/60000]
[51264/60000]
[57664/60000]

**Comment by spzala** [comment]
Fixed merge conflict.

**Comment by spzala** [comment]
cc @HamidShojanazeri

**Comment by usteiner9** [comment]
thanks

**Comment by spzala** [comment]
@svekars hello, considering the changes, I am wondering if I need to request review from any specific reviewer? No rush, I just thought good idea I ask in case it's needed. Thanks!

**Review by suraj813 — APPROVED** [review]
@spzala thank you for improving the tutorial!

**Comment by spzala** [comment]
@suraj813 yrw, and thank you so much for the review!

**Pull request merged**
