### PR TITLE
Fix YouTube beginner tutorial menu

### PR DESCRIPTION
**Pull request by kiersten-stokes**
While going through the beginner YT tutorial, I noticed that the "Training with PyTorch" and "Model Understanding with Captum" topics did not appear on the navigation menu. This PR changes the names of these two files to append `_tutorial` to the end of the `captumyt.py` and `trainingyt.py` files, as well as changes their reference links in the relevant places.

If there is a historical reason that this was not done earlier, please feel free to close

### Before:
Screenshot 2023-01-24 at 12 43 10 PM

### After:
Screenshot 2023-01-24 at 12 43 04 PM

cc @svekars @carljparker

### CODE REVIEW

**Comment by kiersten-stokes** [comment]
Working on CLA 🙂

**Comment by svekars** [comment]
Thank you for contributing to PyTorch. We can enable the tutorial (in the .jenkins/validate_tutorials_built.py) but we don't want to rename them.

**Comment by kiersten-stokes** [comment]
> we don't want to rename them

Fair enough! @svekars Would you be willing to share why? Just wanting to get some insight into what kinds of changes will or won't be accepted 🙂 

> We can enable the tutorial (in the .jenkins/validate_tutorials_built.py)

I believe when I enabled them in a previous commit that I had a handful of related test failures. I'll revert the name changes and attempt enabling the 2 tests in a new commit. If I'm still getting failures, I'll just go ahead and close the PR

**Comment by kiersten-stokes** [comment]
Looks like validation still fails for these 2 tests. Since renaming is not an option and I haven't figured out another way around this, I'll go ahead and close this PR

**Comment by svekars** [comment]
> > we don't want to rename them
> 
> Fair enough! @svekars Would you be willing to share why? Just wanting to get some insight into what kinds of changes will or won't be accepted 🙂 .
> 
Sure, it's for practical reasons—to avoid creating 404 pages or redirects when it can be avoided since we don't have an automatic way to create them. I hope this helps =)

**Comment by kiersten-stokes** [comment]
Makes total sense! I figured it would be something like that. Thanks for taking the time to answer!

**Pull request closed without merging**
