### PR TITLE
Add math explanation

### PR DESCRIPTION
**Pull request by Atcold**
Add an explanation about `x.grad` values.

### CODE REVIEW

**Comment by apaszke** [comment]
Well, these equalities are false. It's like writing `4 * 9 = 36 = 36/2 = 8`. The partial derivative is not equal to a number - either note that you apply it in some point right from the start, or don't put `=` between them.

**Comment by Atcold** [comment]
Hmm... Not quite. `f(x) | x = 1` means `f(x)` computed for the point `x = 1` .
But I change the notation, if you don't like it.

**Comment by apaszke** [comment]
Yeah I know. For example it is valid with definite integrals, because they're actually numbers, so you can write them as functions applied in different points. But partial derivatives are functions and you can't write that you apply them in the middle of equality, because you end up with a function equal to a number.

**Comment by Atcold** [comment]
Fixed. It should be good to go.
Let me know.

**Comment by Atcold** [comment]
Ping.

**Pull request merged**
