### PR TITLE
Fixed colab file related to neural_networks_tutorial 

### LINKED ISSUE #789: Render image in colab
In the [Neural Network colab](https://colab.research.google.com/github/pytorch/tutorials/blob/gh-pages/_downloads/neural_networks_tutorial.ipynb#scrollTo=dhatJ-1_2lFD), the first image in the tutorial doesn't pull in. It only shows the rst: 

image

It should look like [this](https://pytorch.org/tutorials/beginner/blitz/neural_networks_tutorial.html#sphx-glr-beginner-blitz-neural-networks-tutorial-py):
image

### PR DESCRIPTION
**Pull request by anikethc**
Fixes #789 #785 #786  

## Description
fixed Render image in colab, edited correct Correct hyperlink syntax in colab and rst code syntax clean up in colab

### CODE REVIEW

**Comment by anikethc** [comment]
Hi @svekars and @malfet,
Could you please review my pull request ?

**Review by malfet — CHANGES_REQUESTED** [review]
One should never make a PR targeting gh-pages, as this file are auto-generated from the respective.py file in main branch

**Comment by anikethc** [comment]
I am sorry @malfet I did not know that. Should I close this pull request and create another pull request ?

**Comment by malfet** [comment]
@anikethc Up to you. One can repurpose a PR, but if it's too much trouble close and open a new one.

**Pull request closed without merging**
