### PR TITLE
Organize Spatial Transformer Network in a separate Module

### PR DESCRIPTION
**Pull request by rabinadk1**
- Move STN to a different `nn.Module`
- Place sequential executing network in an `nn.Sequential`
- Use Adam instead of SGD
- Use `torch.inference_mode` instead of `torch.no_grad`
- Use `F.cross_entropy` instead of `nn.NLLLoss`

### CODE REVIEW

**Comment by svekars** [comment]
Please fix the syntax error in the build.

**Comment by rabinadk1** [comment]
> Please fix the syntax error in the build.

I used the [script provided in the CONTRIBUTING.md](https://gist.github.com/chsasank/7218ca16f8d022e02a9c0deb94a310fe) to convert the Jupyter Notebook to a Python file. I wonder why it is showing build errors.

**Comment by svekars** [comment]
> Is it because I changed **Author** to **Authors** to include my name?

No, it shouldn't have caused this issue. There is likely a problem lower in the file. You could troubleshoot locally by running just this tutorial.

**Comment by rabinadk1** [comment]
The build shows a syntax error on line 2.

> File "/var/lib/jenkins/workspace/intermediate_source/spatial_transformer_tutorial.py", line 2

I have a working code on [Jupyter notebook](https://colab.research.google.com/drive/12JmJw9hJyPb8qCfyiJ5_SSD3NGDOwGj9?)usp=sharing). Please guide me through the process.

**Comment by svekars** [comment]
> Edit: Why is only one build failing?

That worker builds that tutorial. It is skipped on other workers. You can try to troubleshooting by removing (and saving in some separate file) most lines in that tutorial and then slowly add them back to catch which line causes the formatting issues.

**Pull request closed without merging**
