### PR TITLE
Add windows ci build (#1049)

### PR DESCRIPTION
**Pull request by guyang3532**

### CODE REVIEW

**Comment by brianjo** [comment]
@guyang3532 I reran the test workflow from failed. We're having an issues with downloads during the build.

**Comment by guyang3532** [comment]
> @guyang3532 I reran the test workflow from failed. We're having an issues with downloads during the build.

Thank you. It has passed. Can you review it again? @brianjo

**Comment by guyang3532** [comment]
cc @seemethere

**Comment by brianjo** [comment]
> > @guyang3532 I reran the test workflow from failed. We're having an issues with downloads during the build.
> 
> Thank you. It has passed. Can you review it again? @brianjo

Sounds good. Let's give it a go. :)

**Pull request merged**
